sm/sm-b2b-connector/main/default/objects/B2B_Shipping_Address__c/B2B_Shipping_Address__c.object-meta.xml
<CustomObject>
    <label>B2B Shipping Address</label>
    <nameField>
        <label>B2B Shipping Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>B2B Shipping Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sm/sm-b2b-connector/main/default/objects/B2B_Shipping_Address__c/fields/Cart__c.field-meta.xml
<CustomField>
    <fullName>Cart__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cart</label>
    <referenceTo>WebCart</referenceTo>
    <relationshipLabel>B2B Shipping Addresses</relationshipLabel>
    <relationshipName>B2B_Shipping_Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

sm/sm-b2b-connector/main/default/objects/B2B_Shipping_Address__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

sm/sm-b2b-connector/main/connectorConfigs/objects/B2B_Shipping_Address__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

sm/sm-b2b-connector/main/default/objects/B2B_Shipping_Address__c/fields/Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code__c</fullName>
    <label>Postal Code</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

sm/sm-b2b-connector/main/connectorConfigs/objects/B2B_Shipping_Address__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

sm/sm-b2b-connector/main/default/objects/B2B_Shipping_Address__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <label>Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sm/sm-b2b-connector/main/default/objects/CartItem/fields/B2B_PriceBookEntry_Id__c.field-meta.xml
<CustomField>
    <fullName>B2B_PriceBookEntry_Id__c</fullName>
    <description>Id of price book entry</description>
    <label>B2B PriceBookEntry Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

sm/sm-b2b-connector/main/default/classes/B2BCartToOrderDraftTest.cls
@isTest
private class B2BCartToOrderDraftTest {

    @TestSetup
    static void makeData(){
        System.runAs(RSM_TestEnvironment.portalAccountOwner) {
            TestDataFactory.createData();
            TestDataFactory.createTaxEngine();
        }
    }

    @IsTest
    static void testCartToOrder() {
        Product2 product1 = [SELECT id, Name FROM Product2 WHERE Name = 'Test Product1' LIMIT 1];
        WebCart cart = [SELECT Id, Name, AccountId, OwnerId, WebStoreId, PoNumber, BillingStreet, BillingCity, BillingState, BillingPostalCode, BillingCountry, BillingLatitude, BillingLongitude,
                            (SELECT Id, Street__c, Country__c, City__c, Postal_Code__c, State__c, Name FROM B2B_Shipping_Addresses__r LIMIT 1) 
                            FROM WebCart WHERE Name = 'Cart' LIMIT 1];
        CartItem cartItems = [SELECT Id, AdjustmentAmount, Product2Id, B2B_PriceBookEntry_Id__c, Type, Quantity, ListPrice, SalesPrice, TotalLineAmount FROM CartItem WHERE CartId =: cart.Id];
        PricebookEntry prices = [SELECT Id, UnitPrice, ProductSellingModelId, ProductSellingModel.SellingModelType FROM PricebookEntry WHERE Id =: cartItems.B2B_PriceBookEntry_Id__c LIMIT 1];
        ProductSellingModel model = [SELECT Id, PricingTerm, Name, SellingModelType FROM ProductSellingModel WHERE Id =: prices.ProductSellingModelId LIMIT 1];
        ProrationPolicy prorationPolicy = [SELECT Id FROM ProrationPolicy WHERE RemainderStrategy = 'AddToFirst' LIMIT 1];
        TaxTreatment taxTreatment = [SELECT Id, TaxEngineId, TaxPolicyId FROM TaxTreatment WHERE TaxPolicyId != null AND Status = 'Active' LIMIT 1];
        CartCheckoutSession session = [SELECT id, Name FROM CartCheckoutSession WHERE WebCartId =: cart.Id LIMIT 1];
        CartDeliveryGroup cartDeliveryGroupId = [SELECT Id, DesiredDeliveryDate, DeliverToName, ShippingInstructions, DeliverToStreet, DeliverToCity, DeliverToState, DeliverToPostalCode, DeliverToCountry, DeliverToLatitude, DeliverToLongitude, DeliveryMethodId, CartId FROM CartDeliveryGroup WHERE DeliveryMethodId != null AND CartId = :cart.Id LIMIT 1];
        CartTax CT= new CartTax();
        CT.CartItemId= cartItems.id;
        CT.TaxRate= 10;
        CT.Amount=10;
        CT.Name= 'TestCartTax';
        CT.TaxType='Estimated';    
            CT.TaxCalculationDate=System.today(); 
        insert CT;
        Test.startTest();
        B2BCartToOrderDraft.B2BCartToOrderDraftRequest request = new B2BCartToOrderDraft.B2BCartToOrderDraftRequest();
        request.checkoutSessionId = session.Id;
        request.cartId = cart.Id;
        List<ID> checkList = new List<Id>();
        
            checkList = B2BCartToOrderDraft.cartToOrder(new B2BCartToOrderDraft.B2BCartToOrderDraftRequest[] {request});
       
        System.assertNotEquals(checkList.size(), 0);
        test.stopTest();
	}

    @IsTest
    static void testCartToOrderTermDefined() {
        Product2 product1 = [SELECT id, Name FROM Product2 WHERE Name = 'Test Product1' LIMIT 1];
        Product2 product2 = [SELECT id, Name FROM Product2 WHERE Name = 'Term Product1' LIMIT 1];
        WebCart cart = [SELECT Id, Name, AccountId, OwnerId, WebStoreId, PoNumber, BillingStreet, BillingCity, BillingState, BillingPostalCode, BillingCountry, BillingLatitude, BillingLongitude,
                            (SELECT Id, Street__c, Country__c, City__c, Postal_Code__c, State__c, Name FROM B2B_Shipping_Addresses__r LIMIT 1) 
                            FROM WebCart WHERE Name = 'Cart' LIMIT 1];
        CartItem cartItems = [SELECT Id, AdjustmentAmount, Product2Id, B2B_PriceBookEntry_Id__c, Type, Quantity, ListPrice, SalesPrice, TotalLineAmount FROM CartItem WHERE CartId =: cart.Id];
        PricebookEntry prices = [SELECT Id, UnitPrice, Product2Id, ProductSellingModelId, ProductSellingModel.SellingModelType, ProductSellingModel.PricingTerm, ProductSellingModel.PricingTermUnit FROM PricebookEntry WHERE Product2Id =: product2.Id LIMIT 1];
        ProductSellingModel model = [SELECT Id, PricingTerm, Name, SellingModelType FROM ProductSellingModel WHERE Id =: prices.ProductSellingModelId LIMIT 1];
        ProrationPolicy prorationPolicy = [SELECT Id FROM ProrationPolicy WHERE RemainderStrategy = 'AddToFirst' LIMIT 1];
        TaxTreatment taxTreatment = [SELECT Id, TaxEngineId, TaxPolicyId FROM TaxTreatment WHERE TaxPolicyId != null AND Status = 'Active' LIMIT 1];
        CartCheckoutSession session = [SELECT id, Name FROM CartCheckoutSession WHERE WebCartId =: cart.Id LIMIT 1];
        CartDeliveryGroup cartDeliveryGroupId = [SELECT Id, DesiredDeliveryDate, DeliverToName, ShippingInstructions, DeliverToStreet, DeliverToCity, DeliverToState, DeliverToPostalCode, DeliverToCountry, DeliverToLatitude, DeliverToLongitude, DeliveryMethodId, CartId FROM CartDeliveryGroup WHERE DeliveryMethodId != null AND CartId = :cart.Id LIMIT 1];
        CartTax CT= new CartTax();
        CT.CartItemId= cartItems.id;
        CT.TaxRate= 10;
        CT.Amount=10;
        CT.Name= 'TestCartTax';
        CT.TaxType='Estimated';    
            CT.TaxCalculationDate=System.today(); 
        insert CT;
        Test.startTest();
        update cartItems;
        B2BCartToOrderDraft.B2BCartToOrderDraftRequest request = new B2BCartToOrderDraft.B2BCartToOrderDraftRequest();
        request.checkoutSessionId = session.Id;
        request.cartId = cart.Id;
        List<ID> checkList = new List<Id>();

            checkList = B2BCartToOrderDraft.cartToOrder(new B2BCartToOrderDraft.B2BCartToOrderDraftRequest[] {request});
        System.assertEquals(checkList.size(), 1);
        test.stopTest();
	}

    @IsTest
    static void testCartToOrderChargeProduct() {
        WebCart cart = [SELECT Id, Name, AccountId, OwnerId, WebStoreId, PoNumber, BillingStreet, BillingCity, BillingState, BillingPostalCode, BillingCountry, BillingLatitude, BillingLongitude,
                            (SELECT Id, Street__c, Country__c, City__c, Postal_Code__c, State__c, Name FROM B2B_Shipping_Addresses__r LIMIT 1) 
                            FROM WebCart WHERE Name = 'Cart' LIMIT 1];
        CartItem cartItems = [SELECT Id, AdjustmentAmount, Product2Id, B2B_PriceBookEntry_Id__c, Type, Quantity, ListPrice, SalesPrice, TotalLineAmount FROM CartItem WHERE CartId =: cart.Id];
        PricebookEntry prices = [SELECT Id, UnitPrice, ProductSellingModelId, ProductSellingModel.SellingModelType FROM PricebookEntry WHERE Id =: cartItems.B2B_PriceBookEntry_Id__c LIMIT 1];
        ProductSellingModel model = [SELECT Id, PricingTerm, Name, SellingModelType FROM ProductSellingModel WHERE Id =: prices.ProductSellingModelId LIMIT 1];
        ProrationPolicy prorationPolicy = [SELECT Id FROM ProrationPolicy WHERE RemainderStrategy = 'AddToFirst' LIMIT 1];
        TaxTreatment taxTreatment = [SELECT Id, TaxEngineId, TaxPolicyId FROM TaxTreatment WHERE TaxPolicyId != null AND Status = 'Active' LIMIT 1];
        CartCheckoutSession session = [SELECT id, Name FROM CartCheckoutSession WHERE WebCartId =: cart.Id LIMIT 1];
        CartDeliveryGroup cartDeliveryGroupId = [SELECT Id, DesiredDeliveryDate, DeliverToName, ShippingInstructions, DeliverToStreet, DeliverToCity, DeliverToState, DeliverToPostalCode, DeliverToCountry, DeliverToLatitude, DeliverToLongitude, DeliveryMethodId, CartId FROM CartDeliveryGroup WHERE DeliveryMethodId != null AND CartId = :cart.Id LIMIT 1];
        Test.startTest();
        cartItems.Type = 'Charge';
        cartItems.ListPrice = prices.UnitPrice;
        cartItems.AdjustmentAmount = prices.UnitPrice;
        cartItems.SalesPrice = prices.UnitPrice;
        update cartItems;
        B2BCartToOrderDraft.B2BCartToOrderDraftRequest request = new B2BCartToOrderDraft.B2BCartToOrderDraftRequest();
        request.checkoutSessionId = session.Id;
        request.cartId = cart.Id;
        List<ID> checkList = new List<Id>();

        CartTax CT= new CartTax();
        CT.CartItemId= cartItems.id;
        CT.TaxRate= 10;
        CT.Amount=10;
        CT.Name= 'TestCartTax';
        CT.TaxType='Estimated';    
            CT.TaxCalculationDate=System.today(); 
        insert CT;
       
        checkList = B2BCartToOrderDraft.cartToOrder(new B2BCartToOrderDraft.B2BCartToOrderDraftRequest[] {request});
        
        System.assertEquals(checkList.size(), 1);
        test.stopTest();
	}

    @IsTest
    static void testCartToOrderSimpleProduct() {
        Product2 product1 = [SELECT id, Name FROM Product2 WHERE Name = 'Test Product1' LIMIT 1];
        Product2 product2 = [SELECT id, Name FROM Product2 WHERE Name = 'Test Product2' LIMIT 1];
        WebCart cart = [SELECT Id, Name, AccountId, OwnerId, WebStoreId, PoNumber, BillingStreet, BillingCity, BillingState, BillingPostalCode, BillingCountry, BillingLatitude, BillingLongitude,
                            (SELECT Id, Street__c, Country__c, City__c, Postal_Code__c, State__c, Name FROM B2B_Shipping_Addresses__r LIMIT 1) 
                            FROM WebCart WHERE Name = 'Cart' LIMIT 1];
        CartItem cartItems = [SELECT Id, AdjustmentAmount, Product2Id, B2B_PriceBookEntry_Id__c, Type, Quantity, ListPrice, SalesPrice, TotalLineAmount FROM CartItem WHERE CartId =: cart.Id];
        PricebookEntry prices = [SELECT Id, UnitPrice, ProductSellingModelId, ProductSellingModel.SellingModelType FROM PricebookEntry WHERE Id =: cartItems.B2B_PriceBookEntry_Id__c LIMIT 1];
        PricebookEntry priceProduct2 = [SELECT Id, UnitPrice, Product2Id FROM PricebookEntry WHERE Product2Id =: product1.Id LIMIT 1];
        
        ProrationPolicy prorationPolicy = [SELECT Id FROM ProrationPolicy WHERE RemainderStrategy = 'AddToFirst' LIMIT 1];
        TaxTreatment taxTreatment = [SELECT Id, TaxEngineId, TaxPolicyId FROM TaxTreatment WHERE TaxPolicyId != null AND Status = 'Active' LIMIT 1];
        CartCheckoutSession session = [SELECT id, Name FROM CartCheckoutSession WHERE WebCartId =: cart.Id LIMIT 1];
        CartDeliveryGroup cartDeliveryGroupId = [SELECT Id, DesiredDeliveryDate, DeliverToName, ShippingInstructions, DeliverToStreet, DeliverToCity, DeliverToState, DeliverToPostalCode, DeliverToCountry, DeliverToLatitude, DeliverToLongitude, DeliveryMethodId, CartId FROM CartDeliveryGroup WHERE DeliveryMethodId != null AND CartId = :cart.Id LIMIT 1];
        CartTax CT= new CartTax();
        CT.CartItemId= cartItems.id;
        CT.TaxRate= 10;
        CT.Amount=10;
        CT.Name= 'TestCartTax';
        CT.TaxType='Estimated';    
            CT.TaxCalculationDate=System.today(); 
        insert CT;
        Test.startTest();
        update cartItems;
        B2BCartToOrderDraft.B2BCartToOrderDraftRequest request = new B2BCartToOrderDraft.B2BCartToOrderDraftRequest();
        request.checkoutSessionId = session.Id;
        request.cartId = cart.Id;
        List<ID> checkList = new List<Id>();

        checkList = B2BCartToOrderDraft.cartToOrder(new B2BCartToOrderDraft.B2BCartToOrderDraftRequest[] {request});

        System.assertEquals(checkList.size(), 1);
        test.stopTest();
	}
}