sm/sm-my-community/main/default/objects/SM_Community_Setting__mdt.object
<CustomObject>
    <fields>
        <fullName>CommercePaymentSalesEndpoint__c</fullName>
        <defaultValue>&quot;/services/data/v55.0/commerce/payments/sales&quot;</defaultValue>
        <label>Commerce Payment Sales Endpoint</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NamedCredential__c</fullName>
        <label>Named Credential</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>SM Community Setting</label>
    <pluralLabel>SM Community Settings</pluralLabel>
</CustomObject>

sm/sm-my-community/main/default/classes/SM_PaymentCreateProcessor.cls
public with sharing class SM_PaymentCreateProcessor {
  public static String generatePayment(RequestWrapper requestWrapper) {
    HttpRequest httpRequest = new HttpRequest();
    httpRequest.setHeader('Content-type', 'application/json');
    httpRequest.setMethod('POST');
    String endpoint = getCalloutUrl('Default');
    httpRequest.setEndpoint(endpoint);

    String requestBody = JSON.serialize(requestWrapper, true);
    httpRequest.setBody(requestBody);
    Http http = new Http();
    HttpResponse httpResponse = http.send(httpRequest);

    Map<String, Object> responseObject = (Map<String, Object>) JSON.deserializeUntyped(
      httpResponse.getBody()
    );
    PaymentWrapper paymentWrapper = (PaymentWrapper) JSON.deserialize(
      JSON.serialize(responseObject.get('payment'), true),
      PaymentWrapper.class
    );

    return paymentWrapper.id;
  }

  public static string getCalloutUrl(String settingName) {
    SM_Community_Setting__mdt setting = SM_Community_Setting__mdt.getInstance(
      settingName
    );
    return 'callout:' +
      setting.NamedCredential__c +
      setting.CommercePaymentSalesEndpoint__c;
  }

  public class RequestWrapper {
    public string accountId;
    public decimal amount;
    public string comments;
    public string currencyIsoCode;
    public Datetime effectiveDate;
    public string paymentGatewayId;
    public PaymentMethodWrapper paymentMethod;
    public String phone;
    public string email;
    public map<string, string> additionalData;
  }

  public class PaymentMethodWrapper {
    @AuraEnabled
    public String id;
  }

  public class PaymentWrapper {
    @AuraEnabled
    public String id;
  }
}