sm/sm-b2b-connector/main/default/objects/Related_Product__c/Related_Product__c.object-meta.xml
<CustomObject>
    <label>B2B Related Product</label>
    <nameField>
        <label>B2B Related Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>B2B Related Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sm/sm-b2b-connector/main/default/objects/Related_Product__c/fields/Enabled__c.field-meta.xml
<CustomField>
    <fullName>Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enabled</label>
    <type>Checkbox</type>
</CustomField>

sm/sm-b2b-connector/main/default/objects/Related_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

sm/sm-b2b-connector/main/default/objects/Related_Product__c/fields/Related_Product__c.field-meta.xml
<CustomField>
    <fullName>Related_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>B2B Related Products (Related Product)</relationshipLabel>
    <relationshipName>RelatedProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

sm/sm-b2b-connector/main/default/objects/Related_Product__c/fields/Related_Product_Relation_Type__c.field-meta.xml
<CustomField>
    <fullName>Related_Product_Relation_Type__c</fullName>
    <label>Related Product Relation Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Competitive</fullName>
            </value>
            <value>
                <fullName>Related</fullName>
            </value>
            <value>
                <fullName>RequiredItem</fullName>
            </value>
            <value>
                <fullName>CrossSell</fullName>
            </value>
            <value>
                <fullName>UpSell</fullName>
            </value>
            <value>
                <fullName>Complementary</fullName>
            </value>
            <value>
                <fullName>Accessories</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sm/sm-b2b-connector/main/default/objects/Related_Product__c/fields/Related_Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Related_Product_Type__c</fullName>
    <label>Related Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Competitive</fullName>
            </value>
            <value>
                <fullName>Related</fullName>
            </value>
            <value>
                <fullName>RequiredItem</fullName>
            </value>
            <value>
                <fullName>CrossSell</fullName>
            </value>
            <value>
                <fullName>UpSell</fullName>
            </value>
            <value>
                <fullName>Complementary</fullName>
            </value>
            <value>
                <fullName>Accessories</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sm/sm-b2b-connector/main/default/objects/Related_Product__c/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <label>Sequence</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sm/sm-b2b-connector/main/default/classes/B2B_RelatedProductsHelperTest.cls
@isTest
private class B2B_RelatedProductsHelperTest {

    @testSetup static void main(){
        TestDataFactory.createData();
    }
    static testMethod void first(){
        //Map<String, String> Data = B2BTestFactory.initialStorefrontSetup();
        String AccId= [Select id from Account where Name = 'Test Account'].Id;		//Data.get('accountId');
        String WebStoreId = [Select id,Name from WebStore where Name ='Sflabs' limit 1].id;
        String communityId=	WebStoreId;		///'0DM8c000000sxg1';
        String effectiveAccountId = AccId;
        Product2 product1 =[Select id,Name,Description from Product2 where Name='Test Product1' limit 1];
        Product2 product2 =[Select id,Name,Description from Product2 where Name='Test Product2' limit 1];
        Related_Product__c relatedProduct1 =  new Related_Product__c(
            Product__c = product2.Id, 
            Sequence__c = 1, 
            Related_Product__c = product1.Id,
            Related_Product_Relation_Type__c = 'Related', 
            Related_Product_Type__c = 'CrossSell', 
            Enabled__c = true
        );
        insert relatedProduct1;
        
       ElectronicMediaGroup emg = new ElectronicMediaGroup(); 
        emg.Name= 'Name';
        emg.DeveloperName ='DeveloperName'; 
            emg.UsageType = 'Listing';
        insert emg;
        ElectronicMediaGroup emg1 = new ElectronicMediaGroup(); 
        emg1.Name= 'Name_2';
        emg1.DeveloperName ='DeveloperName_2';
        emg1.UsageType ='Listing';
        insert emg1;
        
        ProductMedia pm = new ProductMedia();		//SELECT ElectronicMediaId, ProductId, ElectronicMediaGroupId, Id FROM ProductMedia
            pm.ProductId = product1.Id;
        pm.ElectronicMediaGroupId = emg.Id;
        pm.ElectronicMediaId = '20Y8Z000000sl9lUAA';
        //insert pm;
        ProductMedia pm2 = new ProductMedia();		//SELECT ElectronicMediaId, ProductId, ElectronicMediaGroupId, Id FROM ProductMedia
            pm2.ProductId = product2.Id;
        pm2.ElectronicMediaGroupId = emg1.Id;
        pm2.ElectronicMediaId = '20Y8Z000000sl9lUAA';
        //insert pm2;
            
       List<Related_Product__c> relatedProduct =  [Select id,Sequence__c,Related_Product__c,Related_Product_Relation_Type__c,Related_Product_Type__c,Enabled__c,Product__c, Product__r.Description, Product__r.Name from Related_Product__c where Product__c=:product1.id];
        
        Map<Id,Related_Product__c> maprelated = new Map<Id,Related_Product__c>();
        for(Related_Product__c i: relatedProduct){
            maprelated.put(i.id,i);
        }
        maprelated.put(relatedProduct1.Id, relatedProduct1);
        Map<String,Object> map_result= new Map<String,Object>(); 
        Map<String,Object> map_result2= new Map<String,Object>();
        ConnectApi.PricingInput pricingInput;
       // Set<Id> productIds= new Set<Id>();
        //productIds.
        B2B_RelatedProductsHelper.ProductDetailResponse onbj = new B2B_RelatedProductsHelper.ProductDetailResponse();
        onbj.prodImageUrl = 'prodImageUrl';
        onbj.isPriceAlreadyAvailable = true;
        onbj.isProductCompared = false;
        onbj.pricingInfo = String.valueOf('abs');
        onbj.isRecurring = true;
        Test.startTest();
		map_result = B2B_RelatedProductsHelper.getRelatedProdDetails(maprelated, communityId, effectiveAccountId);
        System.assert(map_result==null);
        Test.stopTest();
    }
}