sm/sm-b2b-connector/main/default/objects/Related_Product__c/Related_Product__c.object-meta.xml
<CustomObject>
    <label>B2B Related Product</label>
    <nameField>
        <label>B2B Related Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>B2B Related Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sm/sm-b2b-connector/main/default/objects/Related_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

sm/sm-b2b-connector/main/default/objects/Related_Product__c/fields/Related_Product__c.field-meta.xml
<CustomField>
    <fullName>Related_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>B2B Related Products (Related Product)</relationshipLabel>
    <relationshipName>RelatedProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

sm/sm-b2b-connector/main/default/objects/Related_Product__c/fields/Related_Product_Relation_Type__c.field-meta.xml
<CustomField>
    <fullName>Related_Product_Relation_Type__c</fullName>
    <label>Related Product Relation Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Competitive</fullName>
            </value>
            <value>
                <fullName>Related</fullName>
            </value>
            <value>
                <fullName>RequiredItem</fullName>
            </value>
            <value>
                <fullName>CrossSell</fullName>
            </value>
            <value>
                <fullName>UpSell</fullName>
            </value>
            <value>
                <fullName>Complementary</fullName>
            </value>
            <value>
                <fullName>Accessories</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sm/sm-b2b-connector/main/default/objects/Related_Product__c/fields/Related_Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Related_Product_Type__c</fullName>
    <label>Related Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Competitive</fullName>
            </value>
            <value>
                <fullName>Related</fullName>
            </value>
            <value>
                <fullName>RequiredItem</fullName>
            </value>
            <value>
                <fullName>CrossSell</fullName>
            </value>
            <value>
                <fullName>UpSell</fullName>
            </value>
            <value>
                <fullName>Complementary</fullName>
            </value>
            <value>
                <fullName>Accessories</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sm/sm-b2b-connector/main/default/objects/Related_Product__c/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <label>Sequence</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sm/sm-b2b-connector/main/default/classes/B2B_RelatedProductsController.cls
public with sharing class B2B_RelatedProductsController {
    private static final DCM_Logger logger = DCM_Logger.getInstance(B2B_SetupConstants.CHECKOUT_FLOW);

    public static List<String> relatedType = new List<String>{'CrossSell', 'UpSell'};
    public static String addOnType = 'Accessories';

    @AuraEnabled
    public static List<Id> getRelatedProductsByProductId(Id productId){
        try{
            List<Related_Product__c> relatedProductsMap = [SELECT id, Product__c, Product__r.Name, Product__r.Description, Sequence__c, Related_Product_Type__c, Related_Product_Relation_Type__c, Related_Product__r.Name, Related_Product__r.Description
                                                                     FROM Related_Product__c WHERE Related_Product_Type__c in: relatedType AND Product__c =: productId WITH SECURITY_ENFORCED];
            List<Id> ids = new List<Id>();
            for(Related_Product__c relatedProduct : relatedProductsMap){
                ids.add(relatedProduct.Related_Product__c);
            }
            return ids; 
        } catch (Exception ex) {
            logger.error(ex);
            return null;
        } finally {
            logger.flush();
        }

    }
    @AuraEnabled
    public static Map<Id, Id> getRelatedProductsWithCategoriesByProductId(Id productId){
        try{
            List<Related_Product__c> relatedProductsMap = [SELECT id, Product__c, Product__r.Name, Product__r.Description, Sequence__c, Related_Product_Type__c, Related_Product_Relation_Type__c, Related_Product__r.Name, Related_Product__r.Description
                                                                     FROM Related_Product__c WHERE Related_Product_Type__c in: relatedType AND Product__c =: productId WITH SECURITY_ENFORCED];
            List<Id> ids = new List<Id>();
            for(Related_Product__c relatedProduct : relatedProductsMap){
                ids.add(relatedProduct.Related_Product__c);
            }

            Map<Id, Id> result = new Map<Id, Id>();
            for(ProductCategoryProduct category : [SELECT ProductCategoryId, ProductId FROM ProductCategoryProduct WHERE ProductId IN :ids WITH SECURITY_ENFORCED]) {
                result.put(category.ProductId, category.ProductCategoryId);
            }
            
            return result;
        } catch (Exception ex) {
            logger.error(ex);
            return null;
        } finally {
            logger.flush();
        }

    }
    @AuraEnabled
    public static List<Id> getAddOnProductsByProductId(Id productId){
        try{
            List<Related_Product__c> relatedProductsMap = [SELECT id, Product__c, Product__r.Name, Product__r.Description, Sequence__c, Related_Product_Type__c, Related_Product_Relation_Type__c, Related_Product__r.Name, Related_Product__r.Description
                                                                     FROM Related_Product__c WHERE Related_Product_Type__c =: addOnType AND Product__c =: productId WITH SECURITY_ENFORCED];
            List<Id> ids = new List<Id>();
            for(Related_Product__c relatedProduct : relatedProductsMap){
                ids.add(relatedProduct.Related_Product__c);
            }
            return ids; 
        } catch (Exception ex) {
            logger.error(ex);
            return null;
        } finally {
            logger.flush();
        }
    }

    @AuraEnabled
    public static Map<Id, Id> getAddOnProductsCategoryIdsByProductId(Id productId){
        try{
            List<Related_Product__c> relatedProductsMap = [SELECT id, Product__c, Product__r.Name, Product__r.Description, Sequence__c, Related_Product_Type__c, Related_Product_Relation_Type__c, Related_Product__r.Name, Related_Product__r.Description
                                                                     FROM Related_Product__c WHERE Related_Product_Type__c =: addOnType AND Product__c =: productId WITH SECURITY_ENFORCED];
            List<Id> ids = new List<Id>();
            for(Related_Product__c relatedProduct : relatedProductsMap){
                ids.add(relatedProduct.Related_Product__c);
            }

            Map<Id, Id> result = new Map<Id, Id>();
            for(ProductCategoryProduct category : [SELECT ProductCategoryId, ProductId FROM ProductCategoryProduct WHERE ProductId IN :ids WITH SECURITY_ENFORCED]) {
                result.put(category.ProductId, category.ProductCategoryId);
            }
            
            return result;
        } catch (Exception ex) {
            logger.error(ex);
            return null;
        } finally {
            logger.flush();
        }
    }

    @AuraEnabled
    public static List<Id> getAddOnProductsByProductList(List<String> productIds){
        try{
            List<Related_Product__c> relatedProductsMap = [SELECT id, Product__c, Product__r.Name, Product__r.Description, Sequence__c, Related_Product_Type__c, Related_Product_Relation_Type__c, Related_Product__r.Name, Related_Product__r.Description
                                                                     FROM Related_Product__c WHERE Related_Product_Type__c =: addOnType AND Product__c in: productIds WITH SECURITY_ENFORCED];
            List<Id> ids = new List<Id>();
            for(Related_Product__c relatedProduct : relatedProductsMap){
                ids.add(relatedProduct.Related_Product__c);
            }
            return ids; 
        } catch (Exception ex) {
            logger.error(ex);
            return null;
        } finally {
            logger.flush();
        }
    }
    @AuraEnabled
    public static Map<Id, Id> getAddOnProductsWithCategoriesByProductList(List<String> productIds){
        try{
            List<Related_Product__c> relatedProductsMap = [SELECT id, Product__c, Product__r.Name, Product__r.Description, Sequence__c, Related_Product_Type__c, Related_Product_Relation_Type__c, Related_Product__r.Name, Related_Product__r.Description
                                                                     FROM Related_Product__c WHERE Related_Product_Type__c =: addOnType AND Product__c in: productIds WITH SECURITY_ENFORCED];
            List<Id> ids = new List<Id>();
            for(Related_Product__c relatedProduct : relatedProductsMap){
                ids.add(relatedProduct.Related_Product__c);
            }

            Map<Id, Id> result = new Map<Id, Id>();
            for(ProductCategoryProduct category : [SELECT ProductCategoryId, ProductId FROM ProductCategoryProduct WHERE ProductId IN :ids WITH SECURITY_ENFORCED]) {
                result.put(category.ProductId, category.ProductCategoryId);
            }
            
            return result;
        } catch (Exception ex) {
            logger.error(ex);
            return null;
        } finally {
            logger.flush();
        }
    }

    @AuraEnabled
    public static Map<Id, Decimal> getProductPrices(List<String> productId) {
        try{
            Map<Id, Decimal> productPrice = new  Map<Id, Decimal>();
            List<PricebookEntry> prices = [SELECT id, UnitPrice, Product2Id FROM PricebookEntry WHERE Product2Id in: productId WITH SECURITY_ENFORCED];
            for(PricebookEntry entry: prices){
                productPrice.put(entry.Product2Id, entry.UnitPrice);
            }
            return productPrice;
        } catch (Exception ex) {
            logger.error(ex);
            return null;
        } finally {
            logger.flush();
        }
    }
}