sm/sm-b2b-connector/main/connectorConfigs/objects/RSM_Connector_Configuration__mdt/RSM_Connector_Configuration__mdt.object-meta.xml
<CustomObject>
    <label>RSM Connector Configuration</label>
    <pluralLabel>RSM Connector Configurations</pluralLabel>
</CustomObject>

sm/sm-b2b-connector/main/connectorConfigs/objects/RSM_Connector_Configuration__mdt/fields/Config_Type__c.field-meta.xml
<CustomField>
    <fullName>Config_Type__c</fullName>
    <label>Config Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>General</fullName>
                <default>true</default>
                <label>General</label>
            </value>
            <value>
                <fullName>Taxation</fullName>
            </value>
            <value>
                <fullName>Login</fullName>
            </value>
            <value>
                <fullName>Admin Configuration</fullName>
            </value>
            <value>
                <fullName>Invoicing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sm/sm-b2b-connector/main/connectorConfigs/classes/RSM_ConnectorConfigrationSelector.cls
/*
* Use this class only when you want multiple configraion in one tranaction
* if you want to get only one config in transaction you can use standard getInstance method
* i.e Games__mdt mc = Games__mdt.getInstance('FirstRecord');
*/

public with sharing class RSM_ConnectorConfigrationSelector {
    private static Map<String, RSM_Connector_Configuration__mdt> configByDeveloperName {
        get {
            if (configByDeveloperName == null) {
                configByDeveloperName = RSM_Connector_Configuration__mdt.getAll();
            }
            return configByDeveloperName;
        }
        set;
    }

    public String getConfigByDeveloperName(string devName) {
        return configByDeveloperName.get(devName)?.Key__c;
    }

    public Map<String, String> getAllConfigByType(string configType) {
        return ( Map<String, String>) Collection.of([SELECT Id, Key__c,DeveloperName FROM RSM_Connector_Configuration__mdt WHERE Config_Type__c =: configType]).mapBy('DeveloperName', 'Key__c');
    }
}


// RSM_ConnectorConfigrationSelector sel = new RSM_ConnectorConfigrationSelector();
// system.debug(sel.getAllConfigByType(''));